library(tictoc)
library(sparsepca)
library(parallel)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(MASS)
library(ggpubr)
library(grid)
library(sjmisc)
library(nFactors)
library(ggthemes)
library(glue)
library(ggtext)

source('simulation/Schipper_Deun_make_data.R')
source('simulation/SPCA_cv.R')

source('simulation/component_selection_techniques/PA_method.R')
source('simulation/component_selection_techniques/AF_method.R')
source('simulation/component_selection_techniques/OC_method.R')
source('simulation/component_selection_techniques/KG_method.R')
source('simulation/component_selection_techniques/CV_method.R')